export enum WALLETS_EVENTS {
  ACCOUNTS = 'ACCOUNTS',
  CURRENT_PROVIDER = 'CURRENT_PROVIDER',
  CONNECTION_INFO = 'CONNECTION_INFO',
  CONNECTED_CHAINS = 'CONNECTED_CHAINS',
  CONNECT = 'CONNECT',
  ERROR = 'ERROR',
  CLOSE = 'CLOSE',
  SELECT = 'SELECT',
  UPDATED_PROVIDERS_LIST = 'UPDATED_PROVIDERS_LIST'
}
