export enum WALLETS_EVENTS {
  ACCOUNTS = 'ACCOUNTS',
  CURRENT_PROVIDER = 'CURRENT_PROVIDER',
  CURRENT_WALLET = 'CURRENT_WALLET',
  CONNECTED_CHAINS = 'CONNECTED_CHAINS',
  CONNECT = 'CONNECT',
  ERROR = 'ERROR',
  CLOSE = 'CLOSE',
  SELECT = 'SELECT'
}
