export enum WALLETS_EVENTS {
  ACCOUNTS = 'ACCOUNTS',
  CURRENT_WALLET = 'CURRENT_WALLET',
  CONNECTED_CHAINS = 'CONNECTED_CHAINS',
  CONNECT = 'connect',
  ERROR = 'error',
  CLOSE = 'close',
  SELECT = 'SELECT'
}
