export const INJECTED_PROVIDER_ID = 'injected'
export const CACHED_PROVIDER_KEY = 'CACHED_PROVIDER_KEY'
export const CACHED_MULTI_PROVIDERS_KEY = 'CACHED_MULTI_PROVIDERS_KEY'
export const CACHED_PROVIDER_CHAINS_KEY = 'CACHED_PROVIDER_CHAINS_KEY'
